# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
lang: en
url: https://ropemayhem.com/
baseurl: /
title: Ropemayhem
email: info@ropemayhem.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ropemayhem.com" # the base hostname & protocol for your site, e.g. http://example.com
description: >- # the ">" symbol means to ignore newlines until "keywords:"
  News and information related to the shibari/kinbaktu scene in Eurpe.
keywords: shibari kinkibu
navbar_fixed: false
footer_fixed: false
bs_theme: dark

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------
# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag

gems:
  - jekyll-tagging-related_posts

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------
jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tag-archive
    category: category-archive
  permalinks:
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'
  slug_mode: latin

# -----------------------------------------------------------------------------
# Jekyll Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization
feed:
  include:
    - _pages
    - _posts
  excerpt_only: true

# -----------------------------------------------------------------------------
# Sitemap Settings
# -----------------------------------------------------------------------------
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------
enable_google_analytics: true

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

# For Google Analytics, see https://support.google.com/analytics/answer/10447272?hl=en&ref_topic=14088998&sjid=5129943941510317771-SA#zippy=%2Cgoogle-sites
# and follow the instructions for Google Sites. You will need to create a Google Analytics property and copy the Google tag ID.
google_analytics: G-Q6W2HX5TZE

include:
  - _pages

exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

